### ISSUE TITLE
utPLSQL for SQL Developer installation does not work

### ISSUE THREAD

**Issue by steffenschneider** [utPLSQL/utPLSQL-SQLDeveloper#95] opened 2020-03-27 09:32 UTC
In SQL Developer - Help - Check for Updates
I install from local files --> utplsql_for_SQLDev_1.1.1.zip

New Installs: Database - utPLSQL for SQL Developer 
press Finish

To finish installing updates, SQL Developer needs to restart.
Do you want to restart now? --> Yes

After restart utPLSQL for SQL Developer is missing.
I can't find it in Help - About - Extensions.

utPLSQL should be installed.
select substr(ut.version(),1,60) as ut_version from dual;
gives me
UT_VERSION                                                  
v3.1.10.3349

How to install utPLSQL for SQL Developer?
Can I provide more information?

Regards 
Steffen

**Comment by PhilippSalvisberg** [comment] 2020-03-27 09:55
Hi @steffenschneider. Thanks for reporting this. Can you please provide the following information:

1.  Operating System (e.g. Windows 10)
2.  Directory where SQL Developer is installed
3. The user you are working with (e.g. Administrator or normal privileged user)

Thanks.

**Comment by steffenschneider** [comment] 2020-03-27 13:09
Hi @PhilippSalvisberg .

I use Windows 10.

SQL Developer ist installed in --> C:\Program Files (x86)\sqldeveloper

The user is 'SYSTEM' (Administrator).

Thank you for the help. :)

**Comment by PhilippSalvisberg** [comment] 2020-03-27 13:21
In this case you have to start SQL Developer as Administrator (select "Run As" from Context menu) to successfully install Extensions. Otherwise the installation will fail as you've described, even if you are Adminstrator. That's the default behaviour of Windows. See also https://github.com/Trivadis/plsql-cop-sqldev/blob/master/FAQ.md#i-cannot-install-any-extension-on-windows .

Personally, I recommend to install SQL Developer in an unprotected folder such as `C:\apps\`.

**Comment by PhilippSalvisberg** [comment] 2020-03-27 13:34
I assume the issue is solved and close it.

**Closed by PhilippSalvisberg** 2020-03-27 13:34 UTC
Labels: question
